FANTASY_CONNECTION_ERROR_MSG = 'ERROR CONNECTING TO THE FANTASY API'
MISSING_PARAMETERS_ERROR_MSG = 'PARAMETERS REQUIRED: {params}'
ENTRY_DATA_ERROR_MSG = 'THERE WAS A PROBLEM WITH THE DATA RETURNED FROM FPL'
