openapi: '3.0.0'
info:
  title: FPL Stats API Specification
  description: <ap>This document provides a guide for consuming endpoints on the FPL Stats API. The purpose of this service is to return stats from the FPL API. All requests must contain a player_cookie in the query params as this is what the FPL API uses to authenticate requests. This can be found by logging into <a href='https://www.premierleague.com/'>FPL</a> and obtaining the value of the cookie named pl_profile (without the speech marks).<p>The API has an HTTP/RestFul-based interface using elements of Representation State Transfer (REST) methodology. This interface uses commands and parameters embedded in HTTP URL requests and responds with data in a JavaScript Object Notation (JSON) format.</p>
  contact:
    name: FPL Stats API Support
    email: j.roberts07@outlook.com
  version: 1.0.0
servers:
  - url: http://stats-api.fplstats.com
paths:
  /entry_data/{entry_id}:
    get:
      tags:
        - Entry Data
      summary: The entry name and the leagues entered.
      description:
        Returns the leagues that the player with the requested user entry has entered and their name. Only returns leagues with less than fifty entries.
      parameters:
        - $ref: '#/components/parameters/entry_id'
        - $ref: '#/components/parameters/player_cookie'
      responses:
        '200':
          description: The leagues the entry has entered and their name.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/entry_data_success_response'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error_response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_error_response'

  /league_table/{league_id}:
    get:
      tags:
        - League Data
      summary: The live league table for the league ID provided.
      description:
        Returns the league table of the requested league ID with live points and ranking
      parameters:
        - $ref: '#/components/parameters/league_id'
        - $ref: '#/components/parameters/player_cookie'
      responses:
        '200':
          description: The live league table.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/league_table_success_response'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bad_request_error_response'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internal_error_response'

components:
  parameters:
    entry_id:
      name: entry_id
      in: path
      description: The players entry id.
      required: true
      schema:
        type: number
        example: 1476876
    league_id:
      name: league_id
      in: path
      description: The league id.
      required: true
      schema:
        type: number
        example: 1476876
    player_cookie:
      name: player_cookie
      in: query
      description: The cookie provided to the player by the FPL website.
      required: true
      schema:
        type: string
        example: "eyjdjd455TYHdbnmdJFyy7667HSHMNCII9idknfn&jYn=="

  schemas:
    entry_data_success_response:
      type: object
      required:
        - name
        - leagues
      properties:
        name:
          type: string
          description: The name of the entry.
          example: "Team A"
        leagues:
          type: array
          items:
            type: object
            required:
              - id
              - name
            properties:
              id:
                type: number
                description: The id of the league.
                example: 1234
              name:
                type: string
                description: The name of the leagie
                example: "My Fantasy League"

    league_table_success_response:
      type: object
      required:
        - league_id
        - league_name
        - standings
      properties:
        league_id:
          type: string
          description: The ID of the league.
          example: "27364"
        league_name:
          type: string
          description: The name of the league.
          example: "League A"
        standings:
          type: array
          description: The sorted array of current live standings.
          items:
            type: object
            required:
              - entry_id
              - player_name
              - entry_name
              - live_points
              - total_points
              - confirmed_rank
              - live_rank
            properties:
              entry_id:
                type: string
                description: The ID of the entry.
                example: "17983"
              player_name:
                type: string
                description: The name of the player.
                example: "Player A"
              entry_name:
                type: string
                description: The name of the entry.
                example: "Team A"
              live_points:
                type: integer
                description: The number of total points plus the live points.
                example: 100
              total_points:
                type: integer
                description: The number of total points at the start of the gameweek.
                example: 90
              confirmed_rank:
                type: integer
                description: The rank at the start of the gameweek.
                example: 2
              live_rank:
                type: integer
                description: The live rank.
                example: 1

    bad_request_error_response:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "PARAMETERS REQUIRED: player_cookie"

    internal_error_response:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "FPL CONNECTION ERROR"
