version: '2'
services:

  fpl-stats-api:
    build:
      context: ../../fpl-stats-api/src
      dockerfile: Dockerfile
    depends_on:
      - fpl-stats-database
    image: fpl/fpl-stats-api
    ports:
      - "30000:8000"
    volumes:
      - .:/usr/src/app

  fpl-stats-database:
    image: mongo:4.1.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fpl
      - MONGO_INITDB_ROOT_PASSWORD=password

  fpl-stats-api-test:
    build:
      context: ../../fpl-stats-api/src
      dockerfile: Dockerfile.test
    depends_on:
      - fpl-stats-database
    volumes:
      - .:/usr/src/app
